# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
matrix:
    include:
        - php: hhvm
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
          env: deps=high
        - php: 7.0

script: phpunit -c app/ --coverage-text

before_script:
  - composer self-update
  - composer install -n

notifications:
  email: med.ahamada@mit.co.ma
